[build]
  functions = ".netlify/functions"

# Increase function timeout for email operations
[[functions]]
  path = "/api/auth/signup"
  node_bundler = "esbuild"
  timeout = 30

[[functions]]
  path = "/api/debug/*"
  node_bundler = "esbuild"
  timeout = 30

# Environment variables available to functions
[context.production.environment]
  NODE_ENV = "production"

# Headers for CORS if needed
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"